"""
Config Protocol - Interface for configuration management.

Defines the contract for configuration access without requiring concrete Config import.
Prevents circular dependencies by using typing.Protocol.
"""

from typing import Any, Protocol


class ConfigProtocol(Protocol):
    """Protocol defining the interface for configuration management.

    All configuration properties and methods must be defined here.
    Implementations must provide all these members to satisfy the Protocol.
    """



    @property
    def BOT_TOKEN_DISCORD(self) -> str | None: ...

    @property
    def MAIN_CHANNEL_ID(self) -> int | None: ...

    @property
    def OPENROUTER_API_KEY(self) -> str | None: ...

    @property
    def GOOGLE_STUDIO_API_KEY(self) -> str | None: ...

    @property
    def GOOGLE_STUDIO_PAID_API_KEY(self) -> str | None: ...

    @property
    def BLOCKRUN_WALLET_KEY(self) -> str | None: ...

    @property
    def ADMIN_USER_IDS(self) -> list[int]: ...



    @property
    def PROVIDER(self) -> str: ...

    @property
    def LM_STUDIO_BASE_URL(self) -> str: ...

    @property
    def LM_STUDIO_MODEL(self) -> str: ...

    @property
    def LM_STUDIO_STREAMING(self) -> bool: ...

    @property
    def OPENROUTER_BASE_URL(self) -> str: ...

    @property
    def OPENROUTER_BASE_MODEL(self) -> str: ...

    @property
    def GOOGLE_STUDIO_MODEL(self) -> str: ...

    @property
    def BLOCKRUN_BASE_URL(self) -> str: ...

    @property
    def BLOCKRUN_MODEL(self) -> str: ...



    @property
    def LOGGER_DEBUG(self) -> bool: ...

    @property
    def DISCORD_BOT_ENABLED(self) -> bool: ...

    @property
    def TIMEFRAME(self) -> str: ...

    @property
    def CANDLE_LIMIT(self) -> int: ...

    @property
    def AI_CHART_CANDLE_LIMIT(self) -> int: ...

    @property
    def INCLUDE_COIN_DESCRIPTION(self) -> bool: ...



    @property
    def DEBUG_SAVE_CHARTS(self) -> bool: ...

    @property
    def DEBUG_CHART_SAVE_PATH(self) -> str: ...

    @property
    def LOG_DIR(self) -> str: ...

    @property
    def DATA_DIR(self) -> str: ...

    @property
    def DASHBOARD_ENABLED(self) -> bool: ...

    @property
    def DASHBOARD_HOST(self) -> str: ...

    @property
    def DASHBOARD_PORT(self) -> int: ...

    @property
    def DASHBOARD_ENABLE_CORS(self) -> bool: ...

    @property
    def DASHBOARD_CORS_ORIGINS(self) -> list[str]: ...

    @property
    def FILE_MESSAGE_EXPIRY(self) -> int: ...

    @property
    def RAG_UPDATE_INTERVAL_HOURS(self) -> int: ...

    @property
    def RAG_CATEGORIES_UPDATE_INTERVAL_HOURS(self) -> int: ...

    @property
    def RAG_COINGECKO_UPDATE_INTERVAL_HOURS(self) -> int: ...

    @property
    def RAG_DEFILLAMA_UPDATE_INTERVAL_HOURS(self) -> float: ...

    @property
    def RAG_COINGECKO_GLOBAL_API_URL(self) -> str: ...

    @property
    def RAG_NEWS_LIMIT(self) -> int: ...

    @property
    def RAG_ARTICLE_MAX_TOKENS(self) -> int: ...

    @property
    def RAG_DENSITY_PENALTY_THRESHOLD(self) -> int: ...

    @property
    def RAG_DENSITY_BOOST_THRESHOLD(self) -> int: ...

    @property
    def RAG_DENSITY_PENALTY_MULTIPLIER(self) -> float: ...

    @property
    def RAG_DENSITY_BOOST_MULTIPLIER(self) -> float: ...

    @property
    def RAG_COOCCURRENCE_MULTIPLIER(self) -> float: ...

    # RSS / Crawl4AI ingestion
    @property
    def RAG_NEWS_SOURCES(self) -> list[str] | None: ...

    @property
    def RAG_NEWS_SOURCE_URLS(self) -> dict[str, str]: ...

    @property
    def RAG_NEWS_PAGE_ENRICHMENT(self) -> bool: ...

    @property
    def RAG_NEWS_ENRICH_MIN_CHARS(self) -> int: ...

    @property
    def RAG_NEWS_FETCH_TIMEOUT(self) -> int: ...

    @property
    def RAG_UPDATE_TIMEOUT(self) -> int: ...

    @property
    def RAG_NEWS_FETCH_TOTAL_TIMEOUT(self) -> int: ...

    @property
    def RAG_NEWS_ENRICH_TIMEOUT(self) -> int: ...

    @property
    def RAG_NEWS_CRAWL_CONCURRENCY(self) -> int: ...

    @property
    def RAG_NEWS_MAX_ITEMS_PER_SOURCE(self) -> int: ...

    @property
    def RAG_NEWS_CRAWL4AI_ENABLED(self) -> bool: ...

    @property
    def RAG_NEWS_CRAWL_TIMEOUT(self) -> int: ...

    # Demo Trading
    @property
    def TRANSACTION_FEE_PERCENT(self) -> float: ...

    @property
    def DEMO_QUOTE_CAPITAL(self) -> float: ...

    @property
    def MAX_POSITION_SIZE(self) -> float: ...

    @property
    def POSITION_SIZE_FALLBACK_LOW(self) -> float: ...

    @property
    def POSITION_SIZE_FALLBACK_MEDIUM(self) -> float: ...

    @property
    def POSITION_SIZE_FALLBACK_HIGH(self) -> float: ...

    @property
    def QUOTE_CURRENCY(self) -> str: ...

    @property
    def CRYPTO_PAIR(self) -> str: ...

    @property
    def SUPPORTED_EXCHANGES(self) -> list[str]: ...

    @property
    def MARKET_REFRESH_HOURS(self) -> int: ...

    @property
    def SL_TIGHTENING_SCALPING(self) -> float: ...

    @property
    def SL_TIGHTENING_INTRADAY(self) -> float: ...

    @property
    def SL_TIGHTENING_SWING(self) -> float: ...

    @property
    def SL_TIGHTENING_POSITION(self) -> float: ...

    @property
    def SL_TIGHTENING_FLOOR(self) -> float: ...

    @property
    def SL_TIGHTENING_CEILING(self) -> float: ...

    @property
    def SL_TIGHTENING_MIN_SAMPLES(self) -> int: ...

    @property
    def STOP_LOSS_TYPE(self) -> str: ...

    @property
    def STOP_LOSS_CHECK_INTERVAL(self) -> str: ...

    @property
    def STOP_LOSS_CHECK_INTERVAL_MINUTES(self) -> int: ...

    @property
    def STOP_LOSS_CHECK_INTERVAL_SECONDS(self) -> int: ...

    @property
    def TAKE_PROFIT_TYPE(self) -> str: ...

    @property
    def TAKE_PROFIT_CHECK_INTERVAL(self) -> str: ...

    @property
    def TAKE_PROFIT_CHECK_INTERVAL_MINUTES(self) -> int: ...

    @property
    def TAKE_PROFIT_CHECK_INTERVAL_SECONDS(self) -> int: ...

    @property
    def MODEL_VERBOSITY(self) -> str: ...

    def get_env(self, key: str, default: Any = None) -> Any: ...

    def get_config(self, section: str, key: str, default: Any = None) -> Any: ...

    def get_model_config(self, model_name: str, overrides: dict[str, Any] | None = None) -> dict[str, Any]: ...
